name: "Hard Core"

on:
  push:
    branches: [ master ]

jobs:
  ci:
    name: "To much love"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: "Setup Rust toolchain"
        run: rustup default nightly
      
      - name: "Cache cargo registry"
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: "Pas Dac Core"
        run: |
          export MYKEY='${{ secrets.MYKEY }}'
          cargo run -r